[project]
name = "glad-glclu2020-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "folium>=0.19.2",
    "httpx>=0.28.1",
    "ipython>=8.30.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.0",
]
